### ISSUE TITLE
Channels get scrambled when activating new channels

### ISSUE THREAD

**Issue by thiagoburghi** [RTXI/rtxi#166] opened 2024-04-16 10:33 UTC
## Basic Information: 
RTXI Version: 3.0.4
Installed from Live CD?: No
DAQ device: NI PCIe 6259

Error Description: Activating a new DAQ channel in the control panel changes the signal of previously activated channels

What was supposed to happen: signals should remain associated to their correct channels

What steps will trigger the error?
1- Turn on Oscilloscope to monitor signals.
2 - Activate a channel (in the control panel) that is currently receiving a signal and display in oscilloscope. 
Example: channel 3 of our DAQ is just receiving white noise:
![image](https://github.com/RTXI/rtxi/assets/67546053/d4232b28-c399-4d51-87a7-b90a81c6372d)

3- Activate a second channel (in the control panel) that is currently receiving a different signal. The previously activated channel now displays the different signal. Example: after activating channel 6, channel 3 now display the different signal (pink noise):
![image](https://github.com/RTXI/rtxi/assets/67546053/2896fcd9-9220-40fa-930f-d2f312264d4a)

In addition, channel 6 now displays the signal that was previously associated to channel 3:
![image](https://github.com/RTXI/rtxi/assets/67546053/0433d62a-e27f-4c82-b957-af5899559994)

4-Activating new signals keep scrambling the previous channels. Example: activated channel 7, now channel 6 is yet a different signal:
![image](https://github.com/RTXI/rtxi/assets/67546053/03b26cd3-9e2c-4483-a531-fa399cfe7c1c)

While it is now channel 7 that acquired the white noise signal that should have been that of channel 3:
![image](https://github.com/RTXI/rtxi/assets/67546053/ad37c198-f136-43d1-8377-693d89b248d7)

5 - **Deactivating the last activated channel seems to correct everything**. Example: deactivating channel 7 results in channels 3 and 6 having the right signals:
![image](https://github.com/RTXI/rtxi/assets/67546053/c8817b72-303c-4d3c-aca9-1dd4244eb1d5)

The problem is not one with the oscilloscope: recording the signals shows that the data associated to them has indeed been scrambled internally in RTXI. Here is data recorded after step 4:
![image](https://github.com/RTXI/rtxi/assets/67546053/54b514a9-f5f3-4866-a02f-3e8a63bc86cf)

**Comment by fusge** [comment] 2024-04-17 16:22
The error comes from the National Instruments DAQ driver for RTXI. It reads and writes channels in the order the channels are added instead of a "sorted by port number" order. The issue is fixed and should be available in the dev branch soon.

**Comment by fusge** [comment] 2024-04-17 16:25
I merged the fix to the dev branch. Can you confirm that the update fixes the issue on your hardware?

**Comment by thiagoburghi** [comment] 2024-04-19 10:12
I can confirm that the fix worked, thanks!

**Closed** 2024-04-19 16:17 UTC
Labels: bug
